# Set executables.
set(CMAKE_C_COMPILER "cl" CACHE STRING "")
set(CMAKE_CXX_COMPILER "cl" CACHE STRING "")
set(CMAKE_ASM_MASM_COMPILER "ml64" CACHE STRING "")
set(CMAKE_RC_COMPILER "rc" CACHE STRING "")
set(CMAKE_LINKER "link" CACHE STRING "")

# Set C standard.
set(CMAKE_C_STANDARD 11 CACHE STRING "")
set(CMAKE_C_STANDARD_REQUIRED ON CACHE STRING "")
set(CMAKE_C_EXTENSIONS OFF CACHE STRING "")

# Set C++ standard.
set(CMAKE_CXX_STANDARD 20 CACHE STRING "")
set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE STRING "")
set(CMAKE_CXX_EXTENSIONS OFF CACHE STRING "")

# Set MSVC runtime library.
set(CMAKE_MSVC_RUNTIME_LIBRARY "" CACHE STRING "")
set(VCPKG_CRT_FLAG "/MT")

# Set interprocedural optimizations.
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION OFF CACHE STRING "")
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_DEBUG OFF CACHE STRING "")
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELEASE OFF CACHE STRING "")
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_MINSIZEREL OFF CACHE STRING "")
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION_RELWITHDEBINFO OFF CACHE STRING "")

# Set compiler flags.
set(LLVM_C_FLAGS_DEBUG "${VCPKG_CRT_FLAG}d /Zi")
set(LLVM_C_FLAGS_RELEASE "${VCPKG_CRT_FLAG} /GL /DNDEBUG")
set(LLVM_C_FLAGS_MINSIZEREL "${VCPKG_CRT_FLAG} /GL /DNDEBUG")
set(LLVM_C_FLAGS_RELWITHDEBINFO "${VCPKG_CRT_FLAG} /Zi /GL /DNDEBUG")

set(CMAKE_C_FLAGS "/DWIN32 /D_WINDOWS /FC /permissive- /utf-8" CACHE STRING "")
set(CMAKE_C_FLAGS_DEBUG "/Od /Ob0 /GS /RTC1 ${VCPKG_CRT_FLAG}d /Zi" CACHE STRING "")
set(CMAKE_C_FLAGS_RELEASE "/O1 /Oi /Ob2 /GS- ${VCPKG_CRT_FLAG} /GL /DNDEBUG" CACHE STRING "")
set(CMAKE_C_FLAGS_MINSIZEREL "/O1 /Oi /Ob1 /GS- ${VCPKG_CRT_FLAG} /GL /DNDEBUG" CACHE STRING "")
set(CMAKE_C_FLAGS_RELWITHDEBINFO "/O2 /Oi /Ob1 /GS- ${VCPKG_CRT_FLAG} /Zi /GL /DNDEBUG" CACHE STRING "")

set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} /GR /EHsc" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} /await" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} /await /await:heapelide" CACHE STRING "")
set(CMAKE_CXX_FLAGS_MINSIZEREL "${CMAKE_C_FLAGS_MINSIZEREL} /await /await:heapelide" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_C_FLAGS_RELWITHDEBINFO} /await /await:heapelide" CACHE STRING "")

# Set linker flags.
set(CMAKE_STATIC_LINKER_FLAGS "/machine:x64" CACHE STRING "")
set(CMAKE_STATIC_LINKER_FLAGS_DEBUG "" CACHE STRING "")
set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "" CACHE STRING "")
set(CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL "" CACHE STRING "")
set(CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO "" CACHE STRING "")

set(CMAKE_SHARED_LINKER_FLAGS "/machine:x64" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "/debug:fastlink /incremental" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/opt:ref /opt:icf /ltcg" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL "/opt:ref /opt:icf /ltcg" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "/opt:ref /opt:icf /debug:fastlink /ltcg:incremental" CACHE STRING "")

set(CMAKE_MODULE_LINKER_FLAGS "/machine:x64" CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "/debug:fastlink /incremental" CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "/opt:ref /opt:icf /ltcg" CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL "/opt:ref /opt:icf /ltcg" CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "/opt:ref /opt:icf /debug:fastlink /ltcg:incremental" CACHE STRING "")

set(CMAKE_EXE_LINKER_FLAGS "/machine:x64" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS_DEBUG "/debug:fastlink /incremental" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/opt:ref /opt:icf /ltcg" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "/opt:ref /opt:icf /ltcg" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "/opt:ref /opt:icf /debug:fastlink /ltcg:incremental" CACHE STRING "")

# Disable logo for compiler and linker.
set(CMAKE_CL_NOLOGO "/nologo" CACHE STRING "")

# Set assembler flags.
set(CMAKE_ASM_MASM_FLAGS_INIT "/nologo")

# Set resource compiler flags.
set(CMAKE_RC_FLAGS_INIT "/nologo -c65001 -DWIN32")
set(CMAKE_RC_FLAGS_DEBUG_INIT "-D_DEBUG")
