# Set C++ standard.
#set(CMAKE_CXX_STANDARD 20 CACHE STRING "")
#set(CMAKE_CXX_STANDARD_REQUIRED ON CACHE STRING "")
#set(CMAKE_CXX_EXTENSIONS OFF CACHE STRING "")

# Set MSVC runtime library.
#set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>" CACHE STRING "")

# Set interprocedural optimizations.
#set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON CACHE STRING "")

# Set compile definitions.
add_definitions(/DADD_DEFINITIONS)

# Set compile options.
add_compile_options(/DADD_COMPILE_OPTIONS)

# Set link options.
add_link_options(/IGNORE:4199 /DELAYLOAD:ADD_LINK_OPTIONS)

# Set compiler and linker flags.
#set(CMAKE_CXX_FLAGS_INIT "/DCMAKE_CXX_FLAGS_INIT")
#set(CMAKE_CXX_FLAGS_RELEASE_INIT "/DCMAKE_CXX_FLAGS_RELEASE_INIT")

#set(CMAKE_CXX_FLAGS "/DCMAKE_CXX_FLAGS" CACHE STRING "")
#set(CMAKE_CXX_FLAGS_RELEASE "/DCMAKE_CXX_FLAGS_RELEASE" CACHE STRING "")

#set(CMAKE_STATIC_LINKER_FLAGS_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_STATIC_LINKER_FLAGS_INIT")
#set(CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_STATIC_LINKER_FLAGS_RELEASE_INIT")

#set(CMAKE_STATIC_LINKER_FLAGS "/IGNORE:4199 /DELAYLOAD:CMAKE_STATIC_LINKER_FLAGS" CACHE STRING "")
#set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "/IGNORE:4199 /DELAYLOAD:CMAKE_STATIC_LINKER_FLAGS_RELEASE" CACHE STRING "")

#set(CMAKE_MODULE_LINKER_FLAGS_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_MODULE_LINKER_FLAGS_INIT")
#set(CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_MODULE_LINKER_FLAGS_RELEASE_INIT")

#set(CMAKE_MODULE_LINKER_FLAGS "/IGNORE:4199 /DELAYLOAD:CMAKE_MODULE_LINKER_FLAGS" CACHE STRING "")
#set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "/IGNORE:4199 /DELAYLOAD:CMAKE_MODULE_LINKER_FLAGS_RELEASE" CACHE STRING "")

#set(CMAKE_SHARED_LINKER_FLAGS_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_SHARED_LINKER_FLAGS_INIT")
#set(CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_SHARED_LINKER_FLAGS_RELEASE_INIT")

#set(CMAKE_SHARED_LINKER_FLAGS "/IGNORE:4199 /DELAYLOAD:CMAKE_SHARED_LINKER_FLAGS" CACHE STRING "")
#set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/IGNORE:4199 /DELAYLOAD:CMAKE_SHARED_LINKER_FLAGS_RELEASE" CACHE STRING "")

#set(CMAKE_EXE_LINKER_FLAGS_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_EXE_LINKER_FLAGS_INIT")
#set(CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT")

#set(CMAKE_EXE_LINKER_FLAGS "/IGNORE:4199 /DELAYLOAD:CMAKE_EXE_LINKER_FLAGS" CACHE STRING "")
#set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/IGNORE:4199 /DELAYLOAD:CMAKE_EXE_LINKER_FLAGS_RELEASE" CACHE STRING "")

#set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_CXX_STANDARD_LIBRARIES_INIT")
#set(CMAKE_CXX_STANDARD_LIBRARIES_RELEASE_INIT "/IGNORE:4199 /DELAYLOAD:CMAKE_CXX_STANDARD_LIBRARIES_RELEASE_INIT")

#set(CMAKE_CXX_STANDARD_LIBRARIES "/IGNORE:4199 /DELAYLOAD:CMAKE_CXX_STANDARD_LIBRARIES" CACHE STRING "")
#set(CMAKE_CXX_STANDARD_LIBRARIES_RELEASE "/IGNORE:4199 /DELAYLOAD:CMAKE_CXX_STANDARD_LIBRARIES_RELEASE" CACHE STRING "")

#set(CMAKE_RC_FLAGS_INIT "/DCMAKE_RC_FLAGS_INIT")
#set(CMAKE_RC_FLAGS_RELEASE_INIT "/DCMAKE_RC_FLAGS_RELEASE_INIT")

#set(CMAKE_RC_FLAGS "/DCMAKE_RC_FLAGS" CACHE STRING "")
#set(CMAKE_RC_FLAGS_RELEASE "/DCMAKE_RC_FLAGS_RELEASE" CACHE STRING "")

# Disables logo for compiler and linker.
set(CMAKE_CL_NOLOGO "/nologo" CACHE STRING "")

# Disables logo for resource compiler.
set(CMAKE_RC_FLAGS_INIT "/nologo")

function(print_cached_variables)
  foreach(variable
      CMAKE_CXX_FLAGS
      CMAKE_STATIC_LINKER_FLAGS
      CMAKE_MODULE_LINKER_FLAGS
      CMAKE_SHARED_LINKER_FLAGS
      CMAKE_EXE_LINKER_FLAGS
      CMAKE_CXX_STANDARD_LIBRARIES
      CMAKE_RC_FLAGS)
    foreach(suffix "_INIT" "_RELEASE_INIT" "" "_RELEASE")
      set(name "${variable}${suffix}")
      if(DEFINED CACHE{${name}})
        message("set(${name} \"${${name}}\")")
      endif()
    endforeach()
  endforeach()
endfunction()
